baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Cheetah Byte LLC.'

[params]
  author = "Sumiyuru P Alwis"
  description =  "Our ad designs blend aesthetics with strategy. We focus on creating visuals that resonate with your audience, spark interest, and evoke emotions, ensuring your message is delivered with maximum impact."
  image= "/img/blog-img.jpg"